import type { ProductEntry } from '../types/productEntry';

export const DEFAULT_PRODUCTS: ProductEntry[] = [
  {
    id: 'product-1',
    name: 'Digital Planner Mastery',
    subtitle: 'Create & Sell Stunning Digital Planners',
    description: 'Everything you need to design, create, and sell digital planners that customers love. Includes ready-to-use templates, AI prompts, step-by-step guides, and proven strategies for building a profitable digital planner business on Etsy and Gumroad.',
    modules: [
      {
        id: 'module-1-1',
        title: 'Introduction to Digital Planners',
        description: 'Understanding the digital planner market, popular formats (GoodNotes, Notability), and what makes a planner sell.',
      },
      {
        id: 'module-1-2',
        title: 'Design Fundamentals',
        description: 'Color theory, typography, layout principles, and creating cohesive planner aesthetics that appeal to your target audience.',
      },
      {
        id: 'module-1-3',
        title: 'Creating Hyperlinked PDFs',
        description: 'Technical setup for interactive elements, tabs, hyperlinks, and ensuring compatibility across devices and apps.',
      },
      {
        id: 'module-1-4',
        title: 'Marketing & Sales Strategy',
        description: 'Pricing strategies, product photography, SEO optimization, and building a loyal customer base on Etsy and Gumroad.',
      },
    ],
    prompts: [
      'Generate 10 unique digital planner theme ideas for [target audience: busy moms, students, entrepreneurs]',
      'Create a color palette with hex codes for a [aesthetic: minimalist, boho, dark academia] digital planner',
      'Write compelling product descriptions for a digital planner focused on [goal: productivity, wellness, finance tracking]',
      'Suggest 15 essential pages every digital planner should include',
      'Generate social media captions for promoting a new digital planner launch',
    ],
    templates: [
      'Monthly Calendar Spread Template (Sunday/Monday start options)',
      'Weekly Layout Template (vertical & horizontal formats)',
      'Daily Planning Page Template with time blocking',
      'Goal Setting Worksheet Template',
      'Habit Tracker Template (30-day grid)',
      'Budget Planning Template',
      'Notes & Brainstorming Page Template',
      'Hyperlink Navigation Tab Template',
    ],
    checklists: [
      '✓ Research trending planner styles on Etsy',
      '✓ Define target audience and their needs',
      '✓ Choose color palette (5-7 colors)',
      '✓ Select fonts (heading, body, decorative)',
      '✓ Design cover page with branding',
      '✓ Create all core planner pages',
      '✓ Add hyperlinks and test navigation',
      '✓ Export as high-quality PDF',
      '✓ Test on multiple devices (iPad, Android)',
      '✓ Create product mockups for listings',
      '✓ Write SEO-optimized product title & description',
      '✓ Set competitive pricing',
      '✓ Upload to Etsy/Gumroad',
      '✓ Create launch social media content',
    ],
  },
  {
    id: 'product-2',
    name: 'Canva Templates Empire',
    subtitle: 'Build a Profitable Template Business',
    description: 'Master the art of creating and selling Canva templates that generate passive income. From Instagram posts to presentation decks, this complete guide includes design systems, workflow strategies, and everything you need to build a thriving template business.',
    modules: [
      {
        id: 'module-2-1',
        title: 'Canva Template Fundamentals',
        description: 'Understanding Canva Pro features, template types, and what makes templates sell. Market research and niche selection strategies.',
      },
      {
        id: 'module-2-2',
        title: 'Design Systems & Branding',
        description: 'Creating cohesive template collections with consistent branding, color schemes, and design elements that customers can easily customize.',
      },
      {
        id: 'module-2-3',
        title: 'Template Creation Workflow',
        description: 'Efficient workflows for designing multiple template variations, using Canva Brand Kit, and organizing elements for easy customer editing.',
      },
      {
        id: 'module-2-4',
        title: 'Selling & Scaling',
        description: 'Pricing strategies, creating preview images, writing compelling descriptions, and building a sustainable template business.',
      },
    ],
    prompts: [
      'Generate 20 Canva template bundle ideas for [niche: coaches, real estate agents, small businesses]',
      'Create a list of trending social media template types for [platform: Instagram, Pinterest, LinkedIn]',
      'Write a product description for a Canva template bundle that includes [number] templates for [purpose]',
      'Suggest color palettes for [brand style: modern, vintage, luxury, playful] Canva templates',
      'Generate 10 template collection names for [industry: wellness, finance, education]',
    ],
    templates: [
      'Instagram Post Template Set (10 designs)',
      'Instagram Story Template Bundle',
      'Pinterest Pin Template Collection',
      'Social Media Content Calendar Template',
      'Presentation Deck Template (20 slides)',
      'Lead Magnet Template (eBook/Checklist)',
      'Email Newsletter Template',
      'Media Kit Template for Influencers',
      'Pricing Guide Template',
      'Workbook/Worksheet Template Set',
    ],
    checklists: [
      '✓ Identify profitable template niche',
      '✓ Research competitor templates and pricing',
      '✓ Create brand style guide (colors, fonts, elements)',
      '✓ Design template master layouts',
      '✓ Create 10-20 template variations',
      '✓ Test templates for easy customization',
      '✓ Organize layers and elements logically',
      '✓ Create preview mockups (3-5 images)',
      '✓ Write detailed template instructions',
      '✓ Set up Canva share link (view-only)',
      '✓ Write SEO-optimized listing title',
      '✓ Create compelling product description',
      '✓ Price competitively ($15-$45 range)',
      '✓ Upload to Etsy/Gumroad/Creative Market',
      '✓ Promote on Pinterest and Instagram',
    ],
  },
  {
    id: 'product-3',
    name: 'Printable Wall Art Studio',
    subtitle: 'Design & Sell Beautiful Wall Art',
    description: 'Turn your creativity into profit by designing and selling printable wall art. This comprehensive guide covers design techniques, trending styles, print-ready file preparation, and proven strategies for building a successful print-on-demand business on Etsy.',
    modules: [
      {
        id: 'module-3-1',
        title: 'Wall Art Market Overview',
        description: 'Understanding trending art styles, popular sizes, color preferences, and what customers are searching for on Etsy and other marketplaces.',
      },
      {
        id: 'module-3-2',
        title: 'Design Techniques & Tools',
        description: 'Creating professional wall art using Canva, Adobe Illustrator, or Procreate. Typography art, abstract designs, botanical prints, and more.',
      },
      {
        id: 'module-3-3',
        title: 'Print-Ready File Preparation',
        description: 'Technical requirements for printable art: resolution (300 DPI), color modes (RGB vs CMYK), file formats, and creating multiple size variations.',
      },
      {
        id: 'module-3-4',
        title: 'Listing Optimization & Sales',
        description: 'Creating stunning mockups, writing keyword-rich titles, pricing strategies, and building a cohesive shop aesthetic that converts browsers into buyers.',
      },
    ],
    prompts: [
      'Generate 15 trending wall art themes for [room: bedroom, living room, nursery, home office]',
      'Create a list of popular quote ideas for [style: minimalist, motivational, funny, romantic] wall art',
      'Suggest color combinations for [aesthetic: Scandinavian, bohemian, modern farmhouse, coastal] wall art',
      'Write product descriptions for a set of [number] printable wall art pieces featuring [theme]',
      'Generate SEO keywords for [style] wall art targeting [audience]',
    ],
    templates: [
      'Minimalist Line Art Template',
      'Abstract Shapes & Forms Template',
      'Botanical Illustration Template',
      'Typography Quote Template (multiple layouts)',
      'Geometric Pattern Template',
      'Watercolor Background Template',
      'Scandinavian Style Template',
      'Boho/Neutral Aesthetic Template',
      'Nursery Art Template Set',
      'Gallery Wall Collection Template (3-6 pieces)',
    ],
    checklists: [
      '✓ Research trending wall art styles on Etsy',
      '✓ Choose art niche and target audience',
      '✓ Select design tool (Canva/Illustrator/Procreate)',
      '✓ Create art in multiple sizes (8x10, 11x14, 16x20, 18x24)',
      '✓ Ensure 300 DPI resolution for all files',
      '✓ Save in multiple formats (PDF, JPG, PNG)',
      '✓ Create realistic mockups (3-5 per listing)',
      '✓ Write keyword-rich product title',
      '✓ Create detailed product description with print tips',
      '✓ Include size guide and frame recommendations',
      '✓ Set pricing ($4-$12 for digital files)',
      '✓ Add instant download delivery setup',
      '✓ Create cohesive shop banner and branding',
      '✓ Upload to Etsy with all variations',
      '✓ Promote on Pinterest with lifestyle pins',
    ],
  },
];

/**
 * Returns a fresh deep copy of the default products to prevent mutation issues
 */
export function getDefaultProducts(): ProductEntry[] {
  return JSON.parse(JSON.stringify(DEFAULT_PRODUCTS));
}
